### ISSUE TITLE
topicOverTime relativ - Darstellung mehrerer ausgewählter Kurven ...

### ISSUE THREAD

**Issue by Gerretvn** [Docma-TU/tmT#21]
... in einem Koord.system ermöglichen

**Comment by JonasRieger** [comment]
extension of [totRelative](https://github.com/Docma-TU/tmT/issues/18)

**Comment by JonasRieger** [comment]
try `pages = FALSE`, this should satisfy your request - please close issue then, otherwise i need more details
edit: also `topics = c(1, 6, 7)` e.g. for topics number 1, 6 and 7
