### ISSUE TITLE
Einlesefunktion für csv-Dateien

### ISSUE THREAD

**Issue by Gerretvn** [Docma-TU/tmT#25]
Evtl. dafür gesonderte Vignette

**Comment by JonasRieger** [comment]
will be based on [readWordpress](https://github.com/Docma-TU/tmT/blob/master/R/readWORDPRESS.R)

**Comment by JonasRieger** [comment]
see [Commit 335](https://github.com/Docma-TU/tmT/commit/bfae9b8c8fe8735af71f3ac912e7c7e89209ae81)
